name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to create (e.g. v1.2.3)
        required: true
        type: string
      force:
        description: Skip version increment validation (use for re-releases)
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  release:
    uses: keathmilligan/release-infra/.github/workflows/release.yml@master
    with:
      tag: ${{ inputs.tag }}
      force: ${{ inputs.force }}
      package-name: xrepotui

  publish:
    needs: release
    uses: keathmilligan/release-infra/.github/workflows/publish.yml@master
    with:
      tag: ${{ inputs.tag }}
      project-name: xrepotui
      binary-name: xrepotui
      project-type: rust
      targets: >-
        x86_64-apple-darwin,
        aarch64-apple-darwin,
        x86_64-pc-windows-msvc,
        aarch64-pc-windows-msvc,
        x86_64-unknown-linux-gnu,
        aarch64-unknown-linux-gnu,
        x86_64-unknown-linux-musl,
        aarch64-unknown-linux-musl
      tap-repo: keathmilligan/homebrew-tap
      bucket-repo: keathmilligan/scoop-bucket
      packages-repo: keathmilligan/packages
      enable-cargo: true
      enable-install-scripts: true
      enable-homebrew: true
      enable-scoop: true
      enable-chocolatey: false
      enable-winget: false
      enable-apt: true
      enable-rpm: true
      enable-apk: false
      enable-dmg: true
      enable-msi: true
      enable-aur: false
      enable-badges: true
    secrets: inherit
